version: '3.8'

services:
  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "54321:5432"
    volumes:
      - startbucksv2:/var/lib/postgresql/data
volumes:
  startbucksv2:
